### ISSUE TITLE
function to orient edges of skeleton

### ISSUE THREAD

**Issue by adannenberg** [sepehr78/RecursiveCausalDiscovery.jl#5]
Do you have a function that implemements the Meek's rules to orient the edges, where possible?  If so, can you provide an example?

**Comment by sepehr78** [comment]
I am in the process of implementing v-structure identification and Meek rule orientation!

**Comment by adannenberg** [comment]
Great!

_______________________
Alex Dannenberg
33 The Ledges Road
Newton MA 02459
Tel  617.584.8969
***@***.***

**Comment by sepehr78** [comment]
Added v-structure learning and Meek rules in release `0.2.0`!
