### ISSUE TITLE
new documentation needed for v0.2.0

### ISSUE THREAD

**Issue by adannenberg** [sepehr78/RecursiveCausalDiscovery.jl#6]
Please update documentation with an example that generates a full DAG.  Note that the function learn_and_get_skeleton is used in the current Readme but is no longer present in v0.2.0

Can't wait to try it out :D

**Comment by sepehr78** [comment]
Thanks for pointing out the oversight in the readme! Fixed.

Look at `examples/rsl_example_wo_data.jl` for an example that constructs a random DAG, generates data from it, and the learns the CPDAG using RSL-D.
